package com.graphicless.cricketapp.utils

class ApiEndpoints {

    companion object{
        const val EVERYTHING = "everything"
        const val Q = "q"
        const val CRICKET = "cricket"
        const val SORT_BY = "sortBy"
        const val PUBLISH_AT = "publishedAt"
        const val PAGE_SIZE = "pageSize"
        const val NEWS_API_KEY = "apiKey"
        const val COUNTRIES = "countries"
        const val LEAGUES = "leagues"
        const val PLAYERS = "players"
        const val FIXTURES = "fixtures"
        const val TEAMS = "teams"
        const val VENUES = "venues"
        const val STAGES = "stages"
        const val SEASONS = "seasons"
        const val INCLUDE = "include"
        const val RUNS = "runs"
        const val SQUAD = "squad"
        const val OFFICIALS = "officials"
        const val FIXTURE_ID = "fixture_id"
        const val PLAYER_ID = "playerId"
        const val VENUE_ID = "venueId"
        const val TEAM_ID = "teamId"
        const val STAGE_ID = "stageId"
        const val LEAGUE_ID = "leagueId"
        const val SEASON_ID = "seasonId"
        const val TEAM_RANKINGS = "team-rankings"
        const val LIVE_SCORES = "livescores"
        const val TEAMS_BY_TEAM_ID = "teams/{teamId}"
        const val VENUES_BY_VENUE_ID = "venues/{venueId}"
        const val FILTER_POSITION_ID = "filter[position_id]"
        const val FILTER_STARTS_BETWEEN = "filter[starts_between]"
        const val FIXTURES_BY_FIXTURE_ID = "fixtures/{fixture_id}"
        const val SEASONS_BY_SEASON_ID = "seasons/{seasonId}/"
        const val LEAGUES_BY_LEAGUE_ID = "leagues/{leagueId}/"
        const val TEAMS_BY_TEAM_ID_BY_SQUAD_BY_SEASON_ID = "teams/{teamId}/squad/{seasonId}"
        const val STANDINGS_BY_STAGE_BY_STAGE_ID = "standings/stage/{stageId}"
        const val PLAYER_BY_PLAYER_ID = "players/{playerId}"
        const val FIXTURE_DETAILS_SCORE_CARD_INCLUDE = "bowling,batting,runs,localteam,visitorteam"
        const val PLAYER_DETAILS_NEW_INCLUDE = "country,career.season,teams,currentteams"
        const val FIXTURE_OVER_INCLUDE = "balls,runs"
        const val CALL_LIVE_MATCH_INFO_INCLUDE = "localteam,visitorteam,stage,venue,referee,tosswon,firstumpire,secondumpire,tvumpire"
        const val GET_LIVE_SCORE_DETAILS_INCLUDE = "bowling,batting,runs,lineup,balls,localteam,visitorteam"

    }
}